const fs=require('fs'),vm=require('vm');
const sources=['app.js','asama-route-v1578.js','hyakumeizan-route-enrichment-v1579.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n');
const sandbox={console,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{},URLSearchParams,Intl,Date,Math,JSON,Object,Array,Number,String,Boolean,RegExp,Set,Map,Promise,document:{addEventListener:()=>{},getElementById:()=>null,querySelectorAll:()=>[],querySelector:()=>null,createElement:()=>({style:{},appendChild:()=>{},setAttribute:()=>{}}),body:{appendChild:()=>{}},documentElement:{}},window:{confirm:()=>true,addEventListener:()=>{},matchMedia:()=>({matches:false,addEventListener:()=>{}})},navigator:{userAgent:'audit'},localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},sessionStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},location:{search:'',href:'',origin:'',pathname:'/'},crypto:{randomUUID:()=> 'audit'},fetch:async()=>({ok:false,json:async()=>({})}),AbortController:global.AbortController,Image:function(){}};vm.createContext(sandbox);
vm.runInContext(sources+`\nglobalThis.__X={JAPAN_100_MOUNTAINS,representativeCourseOptions,representativeCourseExpandedPointDefs,buildRepresentativeResolvedRoute,canonicalMountainName};`,sandbox,{timeout:30000});
const X=sandbox.__X;let rows=[];
for(const raw of X.JAPAN_100_MOUNTAINS){const m=X.canonicalMountainName(raw),os=X.representativeCourseOptions(m),c=os[0]||null;if(!c){rows.push({raw,mountain:m,courseCount:0,label:'',expandedPoints:0,status:'NO_COURSE',routePoints:[],segments:[]});continue;}const exp=X.representativeCourseExpandedPointDefs(m,c),b=X.buildRepresentativeResolvedRoute(m,c);rows.push({raw,mountain:m,courseCount:os.length,label:c.label||'',expandedPoints:exp.length,status:b.error?'FAIL':'OK',error:b.error||'',routePoints:exp.map(p=>p[1]),segments:(b.segments||[]).map(x=>x.minutes),totalMinutes:(b.segments||[]).reduce((a,x)=>a+(x.minutes||0),0)});}
rows.sort((a,b)=>a.expandedPoints-b.expandedPoints||a.raw.localeCompare(b.raw,'ja'));
const dist={};for(const r of rows)dist[r.expandedPoints]=(dist[r.expandedPoints]||0)+1;
const summary=`SUMMARY mountains=${rows.length} dist=${JSON.stringify(dist)} fail=${rows.filter(r=>r.status!=='OK').length}`;
fs.writeFileSync('HYAKUMEIZAN_ROUTE_DENSITY_V1579.json',JSON.stringify(rows,null,2));fs.writeFileSync('HYAKUMEIZAN_ROUTE_DENSITY_V1579.txt',[summary,...rows.map(r=>`${String(r.expandedPoints).padStart(2)} | ${r.status.padEnd(9)} | ${String(r.totalMinutes||'').padStart(4)}m | ${r.raw} | ${r.label} | ${r.routePoints.join(' -> ')}`)].join('\n')+'\n');console.log(summary);
for(const m of ['浅間山','十勝岳','御嶽','八ヶ岳（赤岳）','羅臼岳','岩手山','常念岳','鹿島槍ヶ岳']){const r=rows.find(x=>x.raw===m);console.log(m,JSON.stringify(r));}
