(()=>{
const $=id=>document.getElementById(id);
let state={mountains:{},generated_at:null,last_audit_at:null,checked_count:0,available_count:0,error_count:0,mountain_count:0};
const meta=window.TRATEN_RESOURCE_MOUNTAINS||{},areaMap=meta.mountainArea||{},order=meta.mountains||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const osmUrl=id=>{const m=String(id||'').match(/^(node|way|relation)\/(\d+)$/);return m?`https://www.openstreetmap.org/${m[1]}/${m[2]}`:''};
const areaSel=$('waterAreaFilter'),mountainSel=$('waterMountainFilter');
function availableMountains(){return order.filter(m=>state.mountains?.[m]?.checked===true&&state.mountains?.[m]?.available===true)}
function setupAreas(){const avail=availableMountains();areaSel.innerHTML='<option value="">山域を選択してください</option>';(meta.areas||[]).filter(([k])=>avail.some(m=>areaMap[m]===k)).forEach(([k,n])=>areaSel.insertAdjacentHTML('beforeend',`<option value="${k}">${esc(n)}</option>`));populateMountains();}
function populateMountains(){const a=areaSel.value,names=availableMountains().filter(m=>areaMap[m]===a);mountainSel.innerHTML=`<option value="">${a?'山を選択してください':'先に山域を選択してください'}</option>`+names.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('');mountainSel.disabled=!a;render();}
function dateLabel(v){if(!v)return '日付不明';const d=new Date(v+'T00:00:00+09:00');return Number.isNaN(d.getTime())?esc(v):`${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`;}
function signalLabel(r){const cls=r.signal==='good'?'good':r.signal==='bad'?'bad':r.signal==='caution'?'caution':'unknown';return `<span class="water-report-signal ${cls}">${esc(r.signal_label||'状態判定なし')}</span>`;}
function reportResultHtml(data){const w=data?.water_source||{},reports=w.reports||[],summary=w.summary||{};const head=`<div class="water-report-result-head"><b>${esc(summary.label||'公開レポートを確認')}</b>${summary.latest_date?`<small>最新 ${dateLabel(summary.latest_date)}${Number.isFinite(summary.age_days)?`（${summary.age_days}日前）`:''}</small>`:'<small>日付付きレポートなし</small>'}</div>`;const rows=reports.length?reports.map(r=>`<a class="water-index-report-item" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer"><div><time>${dateLabel(r.date)}</time>${signalLabel(r)}<span>${esc(r.host||'出典')}</span></div><strong>${esc(r.title||'公開情報')}</strong>${r.snippet?`<p>${esc(r.snippet)}</p>`:''}<em>元ページを開く ↗</em></a>`).join(''):`<div class="water-index-report-empty">最近の公開レポートを確認できませんでした。<br><small>情報がない＝水がない、ではありません。</small></div>`;const extra=w.search_url?`<a class="water-index-search-more" href="${esc(w.search_url)}" target="_blank" rel="noopener noreferrer">Webでもう少し探す ↗</a>`:'';return head+rows+extra;}
async function findReports(btn){if(btn.dataset.loading==='1')return;const mountain=btn.dataset.mountain||'',osmId=btn.dataset.osmId||'',name=btn.dataset.name||'';const target=document.getElementById(btn.dataset.target||'');if(!target)return;btn.dataset.loading='1';btn.disabled=true;const old=btn.textContent;btn.textContent='レポを検索中…';target.classList.remove('hidden');target.innerHTML='<div class="water-index-report-loading">公開検索結果を確認しています…</div>';try{const r=await fetch('/api/water-source-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mountain,osm_id:osmId,name})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);target.innerHTML=reportResultHtml(data);btn.textContent='レポを再検索';}catch(e){target.innerHTML=`<div class="water-index-report-error">レポート検索に失敗しました：${esc(e.message||e)}</div>`;btn.textContent=old||'レポを探す';}finally{btn.disabled=false;btn.dataset.loading='0';}}
function render(){const m=mountainSel.value;const auditStamp=state.last_audit_at||null;const cacheStamp=state.generated_at||null;const stampHtml=auditStamp?`<br><small>最終監査 ${esc(new Date(auditStamp).toLocaleString('ja-JP'))}</small>`:(cacheStamp?`<br><small>キャッシュ更新 ${esc(new Date(cacheStamp).toLocaleString('ja-JP'))}</small>`:'');$('waterIndexStats').innerHTML=`<strong>水場あり ${state.available_count||0}座</strong><br>監査済み ${state.checked_count||0}/${state.mountain_count||300}座${stampHtml}`;const n=$('waterIndexNotice');if((state.checked_count||0)<(state.mountain_count||300)){n.classList.remove('hidden');n.innerHTML=`固定監査は現在 <b>${state.checked_count||0}/${state.mountain_count||300}座</b>。未監査の山はこの選択リストにはまだ表示しません。水場一覧の固定監査を継続中です。`; }else n.classList.add('hidden');if(!m){$('waterIndexList').innerHTML='<div class="water-empty-index">山域 → 山の順に選択すると、確認済み水場候補を表示します。</div>';return;}const v=state.mountains[m];if(!v?.available){$('waterIndexList').innerHTML='<div class="water-empty-index">この山の確認済み水場候補はありません。</div>';return;}const src=(v.sources||[]).slice(0,20).map((x,i)=>{const target=`waterReport_${i}`;return `<div class="water-source-mini"><b>💧 ${esc(x.name||x.kind||'水場')}</b><small>${esc(x.kind||'水場')}・${esc(x.near_point||'ルート付近')}から約${Number(x.distance_m||0).toLocaleString()}m${x.potability==='confirmed'?'・OSM飲用可登録':x.potability==='not_drinking'?'・OSM飲用不可登録':'・OSM飲用可否未確認'}</small><div class="water-source-mini-actions">${osmUrl(x.osm_id)?`<a href="${osmUrl(x.osm_id)}" target="_blank" rel="noopener noreferrer">OpenStreetMapで確認 ↗</a>`:''}<button type="button" class="water-find-report" data-mountain="${esc(m)}" data-osm-id="${esc(x.osm_id||'')}" data-name="${esc(x.name||'')}" data-target="${target}">レポを探す</button></div><div id="${target}" class="water-index-report-box hidden"></div></div>`;}).join('');$('waterIndexList').innerHTML=`<article class="water-mountain-card"><h3>${esc(m)}</h3><div class="water-mountain-meta"><span class="water-chip ok">水場候補 ${v.count||0}件</span>${v.sources?.some(x=>x.potability==='confirmed')?'<span class="water-chip">OSM飲用可登録あり</span>':''}</div><p class="water-search-note">「レポを探す」を押した水場だけ、その時点で公開Web検索を行います。ページを開いただけでは検索しません。</p>${src||'<div class="water-source-mini">候補詳細なし</div>'}</article>`;}
async function load(){try{const r=await fetch('/api/water-mountain-index',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);state=await r.json();setupAreas();}catch(e){$('waterIndexList').innerHTML=`<div class="water-empty-index">水場一覧を取得できませんでした：${esc(e.message||e)}</div>`;}}
areaSel.addEventListener('change',populateMountains);mountainSel.addEventListener('change',render);$('waterIndexList').addEventListener('click',e=>{const btn=e.target.closest('.water-find-report');if(btn)findReports(btn);});load();
})();
